In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
c1 = np.array ([10,12,14,16,18])

In [19]:
c1

array([10, 12, 14, 16, 18])

In [20]:
c1*3

array([30, 36, 42, 48, 54])

In [21]:
b2 = np.zeros(20)

In [22]:
b2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [44]:
x = np.linspace(-4,4,30)

In [49]:
x

array([-4.        , -3.72413793, -3.44827586, -3.17241379, -2.89655172,
       -2.62068966, -2.34482759, -2.06896552, -1.79310345, -1.51724138,
       -1.24137931, -0.96551724, -0.68965517, -0.4137931 , -0.13793103,
        0.13793103,  0.4137931 ,  0.68965517,  0.96551724,  1.24137931,
        1.51724138,  1.79310345,  2.06896552,  2.34482759,  2.62068966,
        2.89655172,  3.17241379,  3.44827586,  3.72413793,  4.        ])

In [37]:
x1 = np.arange (5,10,0.5)

In [32]:
x1

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [39]:
a = (20)
range(20)

range(0, 20)

In [40]:
for i in range (a):
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [52]:
x=y**2

In [53]:
print(x)

[  0.           0.27700831   1.10803324   2.49307479   4.43213296
   6.92520776   9.97229917  13.5734072   17.72853186  22.43767313
  27.70083102  33.51800554  39.88919668  46.81440443  54.29362881
  62.32686981  70.91412742  80.05540166  89.75069252 100.        ]


In [55]:
x= np.sqrt (y)

In [56]:
print(x)

[0.         0.72547625 1.02597835 1.25656172 1.4509525  1.62221421
 1.77704663 1.91942974 2.0519567  2.17642875 2.29415734 2.40613252
 2.51312345 2.61574182 2.71448357 2.80975743 2.901905   2.99121521
 3.07793506 3.16227766]


In [57]:
t=x+y

In [58]:
print(t)

[ 0.          1.25179204  2.07860993  2.83550909  3.55621566  4.25379316
  4.93494137  5.60364027  6.26248302  6.91327086  7.55731523  8.1956062
  8.82891292  9.45784708 10.08290462 10.70449428 11.32295763 11.93858363
 12.55161927 13.16227766]


In [63]:
p=x*y

In [64]:
print(p)

[ 0.          0.38182961  1.07997721  1.98404483  3.05463684  4.26898477
  5.61172621  7.07158325  8.6398177  10.30939934 12.07451231 13.93024088
 15.87235863 17.89718087 20.00145789 22.18229554 24.43709474 26.76350449
 29.15938474 31.6227766 ]
